name = "Cleaner"
uuid = "caabdcdb-0ab6-47cf-9f62-08858e44f38f"
authors = ["Ronald Gamez"]
version = "0.1.0"

[deps]
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
Tables = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
