name = "Cleaner"
uuid = "caabdcdb-0ab6-47cf-9f62-08858e44f38f"
authors = ["Ronald Gamez"]
version = "0.4.0"

[deps]
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
julia = "1.6"
Tables = "1"
